# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6d48df53e8e754ef3397f3c63af3e9179e52d2927da3895f947b87092e624604ad3cbf5c9c95a07abecd0e44dfb5df67677eea3dbae3a129c012ee42cfb8c2a

test:
  secret_key_base: 55bcfe99485b64b55465d270763fca5c063c4f7931030884197da50cb17ce875417ab69b106882f8ab432778979e20e39d7414dcb51be77cac06b963dd508086

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
